### ISSUE TITLE
Deliveries should set price by Zone not by customer

### ISSUE THREAD

**Issue by ciscoLegrand** [CreadixGal/aeksion#103]

**Comment by ciscoLegrand** [comment]
@lucas94gv esto hay que mirar como es....demasiado ambiguo¿?

**Comment by lucas94gv** [comment]
@ciscoLegrand es lo mismo que la pr que hice al mediodia. Se añade un campo precio en zonas y en el create del rate si es delivevery cogemos ese price.

**Comment by lucas94gv** [comment]
Cogo yo esta tarea
